apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ngnix-webserver
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ngnix-webserver
  template:
    metadata:
      labels:
        app: ngnix-webserver
    spec:
      containers:
      - image: ngnix
        name: ngnix-webserver
        ports:
        - containerPort: 80