apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-webserver
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-webserver
  template:
    metadata:
      labels:
        app: nginx-webserver
    spec:
      containers:
      - image: nginx
        name: nginx-webserver
        ports:
        - containerPort: 80