apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  syncPolicy:
    automated:
      prune: true
  source:
    path: env/development/res/nginx
    targetRevision: HEAD
  destination:
    namespace: nginx